import 'dart:io';
import 'dart:math';

import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CovidStatsManager {
  //list of all the countries iso-code_2 in the world,
  //iso codes are unique letters (can be 2 or 3) that is used to identify a country,
  //in this case iso codes are 2 letters
  static const List<String> countryIsoList = [
    'AF',
    'AX',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AR',
    'AM',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'KH',
    'CM',
    'CA',
    'CV',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CG',
    'CD',
    'CK',
    'CR',
    'CI',
    'HR',
    'CU',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KR',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MK',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'AN',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SZ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UM',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW',
  ];

  Future<CovidStatsModel> getRandomCountryCovidData(
      BuildContext context) async {
    //generate random number
    int randomId = Random().nextInt(countryIsoList.length);

    //use random number to get an iso-code from the list
    String url =
        'https://coronavirus-smartable.p.rapidapi.com/stats/v1/${countryIsoList[randomId]}/';
    try {
      var response = await Dio(BaseOptions(headers: {
        'x-rapidapi-key': 'd982c5101bmsh79e1f75480d1b76p10cd36jsn58a599cba848',
        'x-rapidapi-host': 'coronavirus-smartable.p.rapidapi.com'
      })).get('$url');
      if (response.statusCode == 200) {
        return CovidStatsModel.fromJson(response.data);
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(
          '${e.toString()}',
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: Theme.of(context).primaryColor,
      ));
    }

    throw UnimplementedError('No result found');
  }
}

class CovidStatsModel {
  final int totalConfirmedCases;
  final int newlyConfirmedCases;
  final int totalDeaths;
  final int newDeaths;
  final int totalRecoveredCases;
  final int newlyRecoveredCases;
  final String isoCode;
  final String country;

  const CovidStatsModel({
    required this.totalConfirmedCases,
    required this.newlyConfirmedCases,
    required this.totalDeaths,
    required this.newDeaths,
    required this.totalRecoveredCases,
    required this.newlyRecoveredCases,
    required this.isoCode,
    required this.country,
  });

  factory CovidStatsModel.fromJson(Map<String, dynamic> json) {
    return CovidStatsModel(
        totalConfirmedCases: json['stats']['totalConfirmedCases'],
        newlyConfirmedCases: json['stats']['newlyConfirmedCases'],
        totalDeaths: json['stats']['totalDeaths'],
        newDeaths: json['stats']['newDeaths'],
        totalRecoveredCases: json['stats']['totalRecoveredCases'],
        newlyRecoveredCases: json['stats']['newlyRecoveredCases'],
        isoCode: json['location']['isoCode'],
        country: json['location']['countryOrRegion']);
  }

  Map<String, dynamic> toMap() => {
        "iso": isoCode,
        "country": country,
        "total_confirmed_cases": totalConfirmedCases,
        "newly_confirmed_cases": newlyConfirmedCases,
        "total_deaths": totalDeaths,
        "new_deaths": newDeaths,
        "total_recovered_cases": totalRecoveredCases,
        "newly_recovered_cases": newlyRecoveredCases
      };
}
